import os


# Exchanges for PUB SUB
EXPENSES_RABBIT_MQ_EXCHANGE_NAME = 'expenses'
EXPENSES_RABBIT_MQ_QUEUE_NAME = "expenses"
EXPENSES_TASK_NAME = "expenses"
EVENTS_GLOBAL_TASK_NAME = "events_task_worker"
ACCOUNTS_RABBIT_MQ_EXCHANGE_NAME = 'accounts'
ACCOUNTS_RABBIT_MQ_QUEUE_NAME = "accounts"
ACCOUNTS_TASK_NAME = "accounts"

# Exchange types
FANOUT = "fanout"
DIRECT = "direct"

EXCHANGE_QUEUE_BINDING = [
    dict(
        exchange=EXPENSES_RABBIT_MQ_EXCHANGE_NAME,
        queues=[EXPENSES_RABBIT_MQ_QUEUE_NAME, ACCOUNTS_RABBIT_MQ_QUEUE_NAME],
        type=FANOUT
    )
]

DIRECT_QUEUE_ROUTING = {
    EXPENSES_RABBIT_MQ_EXCHANGE_NAME: EXPENSES_RABBIT_MQ_QUEUE_NAME,
    ACCOUNTS_RABBIT_MQ_EXCHANGE_NAME: ACCOUNTS_RABBIT_MQ_QUEUE_NAME
}