apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-deployment
  namespace: backend
  labels:
    app: backend
spec:
  selector:
    matchLabels:
      app: backend
  replicas: 2
  template:
    metadata:
      labels:
        app: backend
    spec:
      imagePullSecrets:
        - name:  pullsecret
      containers:
      - name: backend-server
        image: melvinkimathi/cache-invalidation
        imagePullPolicy: Always
        resources:
          requests:
            cpu: 50m
            memory: 50Mi
          limits:
            cpu: 100m
            memory: 100Mi
        envFrom:
        - secretRef:
            name: backend-env-secret
        - configMapRef:
            name: backend-env-configmap
        ports:
        - containerPort: 5000
          name: http
          protocol: TCP
      restartPolicy: Always