apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  namespace: backend
  name: backend-hpa
  labels:
    app: backend
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: backend-deployment
  minReplicas: 1
  maxReplicas: 3
  metrics:
    - type: ContainerResource
      containerResource:
        name: memory
        container: backend-server
        target:
          type: Utilization
          averageUtilization: 80