apiVersion: v1
kind: Service
metadata:
  name: backend-svc
  namespace: backend
  labels:
    app: backend
spec:
  selector:
    app: backend
  type: NodePort
  ports:
  - name: http
    protocol: TCP
    port: 80
    targetPort: 5000
